### ISSUE TITLE
feat: add vercel toolbar

### ISSUE THREAD

**Issue by srizvi** [yocxo/studio#159]

**Comment by srizvi** [comment]
Needs more brainpower.

```
> @sambi/web@0.1.0 with-env /Users/srs/GitHub/sambi/apps/web
> dotenv -e .env.local -- "next" "dev"

file:///Users/srs/GitHub/sambi/node_modules/@vercel/toolbar/dist/plugins/next.js:4
`)})}).get("/branch",(r,e)=>{e.json({branch:i()})});function E(r){let e=r??x(),t=w((n,c)=>B.handler(n,c));return t.unref(),t.on("error",()=>{}),t.listen(e,()=>{o(`Toolbar dev server listening on port ${e}`),l()}),e}var p=43214;function x(){try{let r=L.sync("node",[h.join(_,"..","scripts","get-free-port.cjs")]);if(!r.stdout&&r.stderr)return o("Unexpected error when getting a free port",r.stderr),p;let e=Number(S(r.stdout).trim());return isNaN(e)?(o(`Error parsing free port: '${r.stdout}'`),p):e}catch(r){return o("Error running the get-free-port script",r),p}}function T(r={}){return e=>{if(process.env.NODE_ENV!=="development")return e;let t=v(),n=i();if(!t)return e;e.env||(e.env={}),o("Found local project info",{...t,gitBranch:n});let c=E(r.devServerPort);return Object.assign(e.env,{VERCEL_TOOLBAR_OWNER_ID:t.ownerId,VERCEL_TOOLBAR_PROJECT_ID:t.projectId,VERCEL_TOOLBAR_BRANCH:n??"",VERCEL_TOOLBAR_DEBUG:process.env.VERCEL_TOOLBAR_DEBUG??"",VERCEL_TOOLBAR_SERVER:`http://localhost:${c}`}),e}}var er=T;export{er as default,T as withVercelToolbar};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^

TypeError: Cannot create property 'env' on string 'phase-development-server'
    at file:///Users/srs/GitHub/sambi/node_modules/@vercel/toolbar/dist/plugins/next.js:4:686
    at normalizeConfig (/Users/srs/GitHub/sambi/node_modules/next/dist/server/config-shared.js:145:18)
    at loadConfig (/Users/srs/GitHub/sambi/node_modules/next/dist/server/config.js:712:68)
    at async nextDev (/Users/srs/GitHub/sambi/node_modules/next/dist/cli/next-dev.js:197:14)
    at async main (/Users/srs/GitHub/sambi/node_modules/next/dist/bin/next:155:5)

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ```
